FROM openjdk:8-jdk-alpine
VOLUME /tmp
ARG JAVA_OPTS
ENV JAVA_OPTS=$JAVA_OPTS
COPY target/ipl-dashboard-0.0.1-SNAPSHOT.jar ipldashboard.jar
EXPOSE 8099
ENTRYPOINT exec java $JAVA_OPTS -jar ipldashboard.jar
# For Spring-Boot project, use the entrypoint below to reduce Tomcat startup time.
#ENTRYPOINT exec java $JAVA_OPTS -Djava.security.egd=file:/dev/./urandom -jar ipldashboard.jar
